### ISSUE TITLE
Different LOCALs in sparky-aptus-upgrade-cron

### ISSUE THREAD

**Issue by ucSec** [sparkylinux/sparky-aptus-upgrade-checker#8]
https://github.com/sparkylinux/sparky-aptus-upgrade-checker/blob/6ccd3f9e937c20c1e05b59aefe10417155f49528/bin/sparky-aptus-upgrade-cron#L57

https://github.com/sparkylinux/sparky-aptus-upgrade-checker/blob/6ccd3f9e937c20c1e05b59aefe10417155f49528/bin/sparky-aptus-upgrade-cron#L58

Why 4h and 8h are different? Thanks.

```sh
CHOICES=`$DIALOG $TITLE"$TITLETEXT" $OKEXIT $MENU $TEXT"$LOCAL7\n\n$LOCAL8" \
Exit "$LOCAL5" \
1h "1 $LOCAL18" \
2h "2 $LOCAL19" \
4h "4 $LOCAL19" \
8h "8 $LOCAL12" \
12h "12 $LOCAL12" \
24h "$LOCAL20" \
7d "$LOCAL21" \
DEL "$LOCAL0" \
UP "$LOCAL26"`
```
I found LOCAL12 is used here:
https://github.com/sparkylinux/sparky-aptus-upgrade-checker/blob/6ccd3f9e937c20c1e05b59aefe10417155f49528/bin/sparky-aptus-upgrade-cron#L147

**Comment by pavroo** [comment]
LOCAL 12 & 19 are the same in English; I separated them due to changes in Polish.
